version: '3'

services:
  app:
    image: 'calculator:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/calculator
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    ports:
      - 8080:8080
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_DB=calculator
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234

